[2025-10-18 02:46:55] [Info] ✅ 日誌建立成功
[2025-10-18 02:46:56] [Info] ✅ 模組快取已清除完畢
[2025-10-18 02:47:00] [Info] ✅ 已載入翻譯詞條數：48
[2025-10-18 02:47:00] [Info] ✅所有初始化作業已完成，正在啟動...
[2025-10-18 02:47:01] [Error] 導入失敗： SqlError: (conn:-1, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 5108ms
    at module.exports.createFatalError (/home/container/node_modules/mariadb/lib/misc/errors.js:91:10)
    at Connection.connectTimeoutReached (/home/container/node_modules/mariadb/lib/connection.js:1410:24)
    at listOnTimeout (node:internal/timers:590:11)
    at process.processTimers (node:internal/timers:523:7)
 From event:
    at /home/container/node_modules/mariadb/lib/connection.js:146:13
    at new Promise (<anonymous>)
    at Connection.connect (/home/container/node_modules/mariadb/lib/connection.js:132:12)
    at Object.createConnection (/home/container/node_modules/mariadb/promise.js:37:17)
    at /home/container/import.js:41:30
    at Object.<anonymous> (/home/container/import.js:98:3)
    at Module._compile (node:internal/modules/cjs/loader:1706:14)
    at Object..js (node:internal/modules/cjs/loader:1839:10)
    at Module.load (node:internal/modules/cjs/loader:1441:32)
    at Function._load (node:internal/modules/cjs/loader:1263:12)
[2025-10-18 02:47:01] [Error] Redis Client Error: Error: Connection timeout
    at Socket.onTimeout (/home/container/node_modules/@redis/client/dist/lib/client/socket.js:180:46)
    at Object.onceWrapper (node:events:633:28)
    at Socket.emit (node:events:519:28)
    at Socket._onTimeout (node:net:604:8)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-10-18 02:47:01] [Error] Redis Client Error: Error: Connection timeout
    at Socket.onTimeout (/home/container/node_modules/@redis/client/dist/lib/client/socket.js:180:46)
    at Object.onceWrapper (node:events:633:28)
    at Socket.emit (node:events:519:28)
    at Socket._onTimeout (node:net:604:8)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-10-18 02:47:01] [Info] ✅ 載入啟動時間: 27.40s (27402.94ms)
[2025-10-18 02:47:01] [Info] %s: %s Bot啟動時間 5.995s
[2025-10-18 02:47:01] [Info] Redis 正在連接...
[2025-10-18 02:47:03] [Info] Redis 正在連接...
[2025-10-18 02:47:03] [Info] Redis 正在連接...
[2025-10-18 02:47:04] [Info] ✅ 壓縮完成： /home/container/log/log-2025-10-18-02-46-55.log.gz
[2025-10-18 02:47:04] [Info] 🗑️ 已刪除舊日誌
[2025-10-18 02:47:04] [Info] Redis 連接測試成功
[2025-10-18 02:47:05] [Warn] ping 測試失敗：[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent: [429 Too Many Requests] You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 57.167614389s. [{"@type":"type.googleapis.com/google.rpc.QuotaFailure","violations":[{"quotaMetric":"generativelanguage.googleapis.com/generate_content_free_tier_requests","quotaId":"GenerateRequestsPerDayPerProjectPerModel-FreeTier","quotaDimensions":{"model":"gemini-2.5-flash","location":"global"},"quotaValue":"250"}]},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Learn more about Gemini API quotas","url":"https://ai.google.dev/gemini-api/docs/rate-limits"}]},{"@type":"type.googleapis.com/google.rpc.RetryInfo","retryDelay":"57s"}]
[2025-10-18 02:47:05] [Warn] ⚠️ 第 1 組 API 金鑰 ping 失敗，嘗試下一組...
[2025-10-18 02:47:05] [Info] Redis 連接測試成功
[2025-10-18 02:47:05] [Warn] ping 測試失敗：[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent: [429 Too Many Requests] You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 54.778017033s. [{"@type":"type.googleapis.com/google.rpc.QuotaFailure","violations":[{"quotaMetric":"generativelanguage.googleapis.com/generate_content_free_tier_requests","quotaId":"GenerateRequestsPerDayPerProjectPerModel-FreeTier","quotaDimensions":{"location":"global","model":"gemini-2.5-flash"},"quotaValue":"250"}]},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Learn more about Gemini API quotas","url":"https://ai.google.dev/gemini-api/docs/rate-limits"}]},{"@type":"type.googleapis.com/google.rpc.RetryInfo","retryDelay":"54s"}]
[2025-10-18 02:47:05] [Warn] ⚠️ 第 2 組 API 金鑰 ping 失敗，嘗試下一組...
[2025-10-18 02:47:05] [Warn] ping 測試失敗：[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent: [429 Too Many Requests] You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 250
Please retry in 56.481823092s. [{"@type":"type.googleapis.com/google.rpc.QuotaFailure","violations":[{"quotaMetric":"generativelanguage.googleapis.com/generate_content_free_tier_requests","quotaId":"GenerateRequestsPerDayPerProjectPerModel-FreeTier","quotaDimensions":{"model":"gemini-2.5-flash","location":"global"},"quotaValue":"250"}]},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Learn more about Gemini API quotas","url":"https://ai.google.dev/gemini-api/docs/rate-limits"}]},{"@type":"type.googleapis.com/google.rpc.RetryInfo","retryDelay":"56s"}]
[2025-10-18 02:47:05] [Warn] ⚠️ 第 1 組 API 金鑰 ping 失敗，嘗試下一組...
